### ISSUE TITLE
What would be a custom engine?

### ISSUE THREAD

**Issue by uhlhosting** [joulez/GoogleCSE#3]
@config plugins.googleCSE.defaultEngine <customEngine>
I tried @config plugins.googleCSE.defaultEngine google.com
Got this: An error has occurred and has been logged. Check the logs for more information.

```
INFO 2016-08-02T11:51:27 "legacy" Search Engine API initialized
ERROR 2016-08-02T11:51:28 Uncaught exception in ['googlecse', 'search'].
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/supybot/callbacks.py", line 1292, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/supybot/callbacks.py", line 1269, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/supybot/commands.py", line 1080, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/him/Limnoria/plugins/GoogleCSE/plugin.py", line 160, in search
    page = self._next(msg.args[0])
  File "/home/him/Limnoria/plugins/GoogleCSE/plugin.py", line 127, in _next
    return self.engine[caller].next()
  File "/home/him/Limnoria/plugins/GoogleCSE/local/GoogleAPI.py", line 233, in next
    self._execute()
  File "/home/him/Limnoria/plugins/GoogleCSE/local/GoogleAPI.py", line 264, in _execute
    raise GoogleAPIError(self.__class__, self.response)
GoogleCSE.local.exceptions.GoogleAPIError: '(Legacy) 403: The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)'
ERROR 2016-08-02T11:51:28 Exception id: 0x6eef0
```

**Comment by joulez** [comment]
Sorry for not replying earlier. This exception pretty much deprecates the legacy engine as google appears to have finally discontinued this api.
