### ISSUE TITLE
GoogleAPIError: '(CSE) 400: Invalid Value: invalid'

### ISSUE THREAD

**Issue by progval** [joulez/GoogleCSE#4]
Hi,

Someone at #supybot just reported the following error when trying to search using GoogleCSE:

```
INFO 2016-08-09T20:01:04 googlecse search called in private by "appe!~milda@81-228-202-215-no69.tbcn.telia.com".
INFO 2016-08-09T20:01:04 "cse" Search Engine API created with custom engine ID "google"
ERROR 2016-08-09T20:01:05 Uncaught exception in ['googlecse', 'search'].
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/supybot/callbacks.py", line 1292, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/callbacks.py", line 1269, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/commands.py", line 1080, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/milda/conf/conf-limnoria/plugins/GoogleCSE/plugin.py", line 160, in search
    page = self._next(msg.args[0])
  File "/home/milda/conf/conf-limnoria/plugins/GoogleCSE/plugin.py", line 127, in _next
    return self.engine[caller].next()
  File "/home/milda/conf/conf-limnoria/plugins/GoogleCSE/local/GoogleAPI.py", line 233, in next
    self._execute()
  File "/home/milda/conf/conf-limnoria/plugins/GoogleCSE/local/GoogleAPI.py", line 264, in _execute
    raise GoogleAPIError(self.__class__, self.response)
GoogleAPIError: '(CSE) 400: Invalid Value: invalid'
ERROR 2016-08-09T20:01:05 Exception id: 0x7a3f7
```

**Comment by joulez** [comment]
"google" is not a valid engine ID. Regards.
